### ISSUE TITLE
Are streaming replies ordered?

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#130]
When digging through the docs i noticed [Streaming Replies](https://github.com/Originate/exosphere-website/blob/master/tutorial/part_2/part_2a/06_communication_format.md#streaming-replies) and an example where it is assumed that reply order is kept (`result += payload`). In this example, if chunks are very small, it could happen that message order is shuffled, for example when allocating a bad connection.

**Comment by kevgo** [comment]
Good catch! Yes, I think even ZeroMQ doesn't guarantee ordering, because that would add a lot of overhead and impact performance. We have 3 options here:

1. leave it as is: the fastest and simplest option. Has some side effects that you point out.

2. add some simple logic that guarantees messages are in order, by adding a counter field to the message. It would not re-transmit dropped messages, so not guarantee that messages are delivered at all.

3. guarantee message ordering and transmission: Messages would be re-transmitted by ExoCom until they are acknowledged by the receiving service instance.

I think there is no single best solution here, and different scenarios require different strategies here. So this should be configurable per application. What do you think?

**Comment by arekkas** [comment]
I will come back to your suggestions in a few, but I want to understand something first. Let's assume that, in the example, the file reader is scaled (2 instances). Wouldn't it be possible for our callback to miss a few responses?

**Comment by arekkas** [comment]
> leave it as is: the fastest and simplest option. Has some side effects that you point out.

If so, this should be clearly documented or a different example should be shown. Concurrency and distributed computing isn't something a lot of people have experience with and most of them will get it wrong.

> add some simple logic that guarantees messages are in order, by adding a counter field to the message. It would not re-transmit dropped messages, so not guarantee that messages are delivered at all.

That's ok if https://github.com/Originate/exosphere-sdk/issues/130#issuecomment-242432442 works fine.

> guarantee message ordering and transmission: Messages would be re-transmitted by ExoCom until they are acknowledged by the receiving service instance.

That's what AMQP does, right?

**Comment by kevgo** [comment]
> Wouldn't it be possible for our callback to miss a few responses as messages are delivered to either instance 1 or instance 2? 

In my current thinking, all replies (simple or streaming) need to arrive at the exact same service instance that made the request. This instance is waiting for the reply in order to process it. Another instance of this service wouldn't know what to do with the reply.

Example: a web server instance receives a POST request to update the user's email. It sends out an `user.update userId: 123, email: 'new@acme.com', messageId: 456` message. The users service replies with `user.updated replyTo: 456` message. ExoCom routes this to the web server instance that sent the message with id 456. The web server instance receives this reply, and then performs a redirect to the user profile.

**Comment by kevgo** [comment]
Re https://github.com/Originate/exosphere-sdk/issues/130#issuecomment-242433306:

Yes, once we decide on the desired behavior here, I'm going to document this in more detail. Right now this is still in the idea stage, waiting for exactly the type of feedback you give here. Thanks for that!

And yes, AMQP re-tries failed messages and puts them on a [dead-letter-exchange](https://www.rabbitmq.com/dlx.html) when they expire. We could do something similar. A notable difference to Exocom is that AMQP doesn't re-try towards the same consumer instance.

**Comment by arekkas** [comment]
> In my current thinking, all replies (simple or streaming) need to arrive at the exact same service instance that made the request. This instance is waiting for the reply in order to process it. Another instance of this service wouldn't know what to do with the reply.

I think that makes sense!

> And yes, AMQP re-tries failed messages and puts them on a dead-letter-exchange when they expire. We could do something similar. A notable difference to Exocom is that AMQP doesn't re-try towards the same consumer instance.

I didn't know AMPQ is doing that. Is there a way to change this?

**Comment by arekkas** [comment]
I think it's ok to not deal with message order and leave it to the implementor. It should however be totally clear to anyone that in the lifetime of any application, the following things will happen:

1. messages will not arrive
2. messages will arrive delayed
3. messages will arrive scrambled
4. messages will arrive in random order
5. ack will be lost

Doing stuff over the network is cool and a framework like exo should remind us thorougly and often of the pitfalls :)

**Comment by arekkas** [comment]
What would happen in this scenario if two services reply to `'file.read'`? Would the callback be called twice?

**Comment by arekkas** [comment]
> I think it's ok to not deal with message order and leave it to the implementor. 

I reconsidered. I remember us talking about streaming and you saying that chunking it up is the best way to solve this over the network. I think streaming is something that happens quite regular and should be supported natively by exoRelay. I don't care if it's chunking things up in the background or doing other magic, but I think it's important to support streaming in the high level API.

**Comment by kevgo** [comment]
>> AMQP re-tries failed messages and puts them on a dead-letter-exchange when they expire. 

> I didn't know AMPQ is doing that. Is there a way to change this?

Actually, I misled you slightly. RabbitMQ is doing that. AMQP is just a protocol. This behavior is specific to the implementation of the message queue I think. Afaik the DLX is just another exchange/queue with a special name.

**Comment by arekkas** [comment]
I see, thanks for clarification!

**Comment by kevgo** [comment]
> It should however be totally clear to anyone that in the lifetime of any application, the following things will happen:
1. messages will not arrive
2. messages will arrive delayed
3. messages will arrive scrambled
4. messages will arrive in random order
5. ack will be lost

Great points. (1) and (2) are just realities of distributed computing we have to live with. I think ZMQ prevents (3) from happening by guaranteeing that messages are delivered atomically. We could add a config setting that deals with (4) and (5), at the cost of having to queue up messages sometimes, which impacts availability, uptime, and memory consumption/GC pressure of services. 

In general I'm all for providing higher-level communication primitives as a framework service to applications. The ExoRelay's could do most of this. If many applications reinvent a wheel, it should become a part of the framework. One of Exosphere's goals is to make distributed computing easy and fun, so this would fit right in. 

You are 100% right that we have to educate app developers about the general problem with distributed computing, and the pros and cons of each config setting available to them though. So that they don't just activate all features and then wonder why their app is slow and bloated and still not 100% reliable.

**Comment by arekkas** [comment]
> We could add a config setting that deals with (4) and (5), at the cost of having to queue up messages sometimes, which impacts availability, uptime, and memory consumption/GC pressure of services. 

I think it should be a different API method. This is very verbose and you can always choose the right method. Something like (exemplary naming):


```
exo.Send()
exo.Stream()
exo.SendAndAknowledge()
```

**Comment by kevgo** [comment]
> What would happen in this scenario if two services reply to 'file.read'? Would the callback be called twice?

Normally only one service gets a message, so there will be only 0-1 replies. Are you talking about rare edge cases where a message gets delayed, it is therefore re-sent by the sender, and then both get processed and cause a reply?

This will be addressed with our upcoming [boundary enforcement milestone](https://github.com/Originate/exosphere-sdk/milestone/17). Exosphere messages are specified via metadata in regards to:
- what fields they have
- whether these fields are required or optional
- the data type of the field's values (string, integer, list, etc)
- their frequency (is it a one-time message or streaming message)

Exosphere will help monitor these things and notify the user about deviations. I think multiple replies to an idempotent message can be treated as a single reply. So if the message is configured as idempotent, the callback would be called only once for the first valid reply, with subsequent ones ignored. Only messages marked as streaming will cause multiple invocations of the callback, but only once for each message id.

**Comment by arekkas** [comment]
> Normally only one service gets a message, so there will be only 0-1 replies. Are you talking about rare edge cases where a message gets delayed, it is therefore re-sent by the sender, and then both get processed and cause a reply?

In our discussion I understood this differently. I thought that one message `userinfo.get` could be answered by a variety of services (one for each basic info, profile picture, statistics, ...) and the sender has to decide which is the highest quality message.

My question assumed that scenario.

**Comment by kevgo** [comment]
I see. In this case, the multiple replies are intentional, so all of them should be handled. There are several ways to go about this:

1. keep the infrastructure simple and call the same callback multiple times, letting the app aggregate the data and decide when it has enough data

2. the app tells Exosphere that it expects X replies within Y ms, and after either X or Y has happened, Exorelay calls the callback once with all replies received so far. 

There is also middle ground: call the callback for each incoming reply, but with a flag that says "this is just preliminary, I'm still waiting on more data". Then when X or Y has happened, make a final callback saying "this is it". This gives the app a chance to precompute results, which shortens the time to process the final callback.

**Comment by arekkas** [comment]
All approaches have their up and downsides. (1) can become quite complex & buggy very quickly if developers don't anticipate this (2) has a negative impact on memory management and has a minimum wait time of Y ms (3) sounds very opinionated and hard to set up (how to define the final message?)

I understand now better what exo is trying to solve and I think that these things are decisions that will impact the top-level API and thus the way people can write software with the SDK (or not). I think developers will reach the point very quickly, where they need to do one of the cases mentioned above and my current feeling is like none of them are really decided yet.

On a side note: I feel that the current tooling does not help developers to think about scaling (`heroku scale ps:web=10`) and failing (chaosmonkey) things. I think it will be crucial for the SDK's success if these things make it into master before the famous hackernews post kicks off: *Exosphere isn't only about helping you code, it's also teaching you how to run things when you develop.*

**Comment by kevgo** [comment]
(2) will also call the callback when it receives all expected messages (X). So assuming the backend is fast, it wouldn't result in more slowdown than if the app waits on its own. (3) would indeed be more opinionated, but some convention has to be followed here anyways, so why not standardize it. 

You are right that we haven't decided some of these questions yet. That was intentional - these decisions should be driven by real-world requirements, not be over-engineered upfront. We have good ideas here, but not finalized the decision.

You hit the nail on the head in the last paragraph: A big benefit of the Exosphere SDK is guiding developers to write software correctly. Meaning against explicit functional, performance, security, and reliability requirements, that are regularly checked by the framework. I agree this should end up in the SDK before sharing with a wider public.

**Comment by arekkas** [comment]
> That was intentional - these decisions should be driven by real-world requirements, not be over-engineered upfront. We have good ideas here, but not finalized the decision.

Good enough for me :) Do you want to keep this issue open?

**Comment by kevgo** [comment]
This was a great conversation, but let's keep the open issues actionable. Closing this for now. It will live on in the product!  :)
