### ISSUE TITLE
How does message delivery work on scaled instances?

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#131]
I have service A and B. Service B is scaled 10 times. Service A broadcasts a message B knows. Is

1. each instance receiving the same message or
2. is only one instance receiving the message?

**Comment by kevgo** [comment]
We let ZeroMQ be the ventilator for messages, so only one instance of service B receives a message. In the scenario you describe possibly different instances.

**Comment by arekkas** [comment]
Would it be possible to broadcast the message to all instances of B?

Use case: A service for real time analytics computes latest messages and keeps results in memory. All instances should have the same state. There is no persistence required because data becomes obsolete after a few minutes.

Gesendet mit meinem HTC

----- Reply message -----
Von: "Kevin Goslar" <notifications@github.com>
An: "Originate/exosphere-sdk" <exosphere-sdk@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Author" <author@noreply.github.com>
Betreff: [Originate/exosphere-sdk] How does message delivery work on scaled instances? (#131)
Datum: Do., Aug. 25, 2016 16:09

We let ZeroMQ be the ventilator for messages, so only one instance of service B receives a message. In the scenario you describe possibly different instances.

**Comment by kevgo** [comment]
I'd say if you want shared computed state, and it is important that it is consistent across instances of a horizontally scaled service B, then it's challenging to compute it 10 times in parallel in different instances of service B and hope it will always end up looking exactly the same, given that messages can get lost etc. It also feels a bit like a distributed computing anti-pattern. For example, this isn't really horizontally scalable, since all clients still have to do the same work. So when you exceed the compute capacity of one instance, adding more doesn't really help here. I have two ideas here:

1. Store the shared mutable state in a dedicated shared in-memory date structure like MemCache. Instances of service B read it from there. You are still running into "shared mutable state" issue like lost update problem here.

2. Make computing the state an explicit operation in your processing pipeline: service A broadcasts updates to a new "compute shared state" service. This service sends the current state to service B, which then uses it for its real-time analytics.

**Comment by arekkas** [comment]
Makes sense :+1:

**Comment by arekkas** [comment]
The example I gave was misleading. Broadcasting makes sense when you want application state available in memory constently throught all scaled instances. But I don't think this is something exo should solve as it can be achieved with storage solutions like rethink.
