### ISSUE TITLE
Layer 1b: backend services

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#133]
The [docs](https://github.com/Originate/exosphere-website/blob/master/tutorial/part_1/02_architecture.md#levels) mention layer 1b which will run third party services like databases, caching, search.

How will those be attached to services? For example: One mysql instance / mysql database per service (e.g. TweetService, UserService)?

**Comment by kevgo** [comment]
I think a good rule is "one database per service". If two services share one database, they are really one service and should be merged (or the database split up between them). 
If other services want to access data from that database, they have to ask the respective service for it.

**Comment by arekkas** [comment]
I think that makes sense and also kind of what I expected.

For my own understanding: In the apps I wrote so far, bottlenecks where almost always database access and password hashing. Wouldn't one database service for the whole infrastructure somehow negate some of the benefits I get from microservices? A simple user service that looks up `users.get` in a SQL database is apart from de/encoding json and waiting for SQL not doing a lot. To increase performance I would probably have to introduce some sort of caching or scale the SQL cluster or improve networking latency between service and database.

Is this a topic that exo will touch?

**Comment by kevgo** [comment]
I'm not sure I fully understand what you mean here. Some general thoughts around this. There will be several micro-services in this scenario:
- user service: stores only real user account data (name, email, date of birth, etc)
- password auth service: stores hashes of passwords and user ids (ids generated by the user service). If generating password hashes is slow, then write this (tiny) service in a fast language and use a fast and scalable key-value store here, and scale it horizontally
- session service: stores data about the current session (user data, last activity done etc) encoded with the session token in a fast key-value store
- password reset service: stores info to reset passwords (reset token, expiration date, user id)

All of these services have small and simple data models and can therefore use fast and simple NoSQL storage systems for persistence. Storing operational user data in an extremely fast in-memory system in the sessions service takes a lot of pressure of the main user database in the users service, which doesn't have to be queried for each request anymore. 

Does this make sense?

**Comment by arekkas** [comment]
Absolutely. In the user scenario, the user service is not much more than providing an exo relay interface to the database. In that case, issues with response times would most likely be subject to

1. the network
2. the database (noSQL or maybe mySQL).

The second point will be even more cirtical when the whole system is using the same noSQL instance.

Now, the question is: I get more benefits from scaling the database up (adding more disk space, adding more cpu/memory, adding nodes) than I would from scaling the user service up. And scaling persistent services is really hard. So, will exo make this easy for me or is this something I have to figure out.

**Comment by kevgo** [comment]
Yes, scaling databases is a hard problem. Exo doesn't add any magic bullets here. But it alleviates a number of issues that contribute to why scaling databases is so hard. For example, it helps break up monolithic databases into many much smaller and simpler ones. This has a number of benefits:

1. simplicity: scaling a large monolithic database that serves many different types of traffic is hard or even impossible. On the other hand, the performance of a small and simple database, which only consists of a few tables, needs just a few indexes, and serves a few types of queries, can be much easier understood, debugged, and optimized, even by an average ops team. Just monitor a few key metrics and best practices, and you get a real fighting chance here. 

2. more freedom: If what the database has to do is much simpler, I can use much easier to scale NoSQL systems. I can also combine different databases much easier. Wanna try out Datomic or RethinkDB without betting the whole project on them? Make one of the services use them, with a backup service that uses a more conventional database just in case and runs in parallel (it sees all queries and responds to them in the same way), and you can try it out in production without much risk. If the shiny new database technology doesn't work out, rewrite this one service to use a different database in a week. Migration of the data is also much easier in this case, because its much simpler structured.

3. less interference: If my data is distributed across several databases, I can run each one on its own system (database cluster), without interference from other types of traffic and queries (that one query from dashboard just invalidated most of the database cache, no wonder all other queries became slower).

So, similar to the code base, the data base layer in Exo is a lot less monolithic, tightly coupled, and complex, at the cost of having more database systems running (hundreds of them). Running simple database systems can be automated in regards to deployment, monitoring, adding machines etc. I think there is a lot Exo can help here. 

Its still hard enough, so the first build-out doesn't include our own hosted databases though. We'll lean on third-party persistence for now. But again, this can be added easily if we want to. I don't see any roadblocks here.

**Comment by arekkas** [comment]
Thank you for the read. All of the stated points make sense and I think it would be awesome to have a best practices section where this could be summed up.

In total, I overlooked that using one database instance for all per default does not prevent you from creating a second database instance that serves only one specific service. Is data is isolated anyways, this is a very easy move.

If you remember, I mentioned that concrete best practices in micro services are rare. Maybe adding a simple handbook or as a blog series - it would be great SEO, backlinks and reposts.

**Comment by kevgo** [comment]
I'd go one step further. It sounds like you still treat your database server as a pet instead of as cattle. Meaning you give a particular machine a name, and are sad when it dies. It's better to treat servers as a herd of cattle. They don't have names, and if the herd becomes too small, you just buy a few more and add them to the herd, without caring who they are. Okay brutal analogy for me as a vegetarian...

But the point is that in a cloud environment, especially with low-cost containers like Docker and ubiquitous infrastructure automation, we shouldn't be afraid to spin up hundreds of different services and servers, persistent or not. If that thought scares us, we need more infrastructure automation. Let's build it!

**Comment by arekkas** [comment]
> It sounds like you still treat your database server as a pet instead of as cattle. 

I don't understand the analogy :) Instead of instance, I should have written cluster. When one mysql cluster isn't able to handle all workload, you just add another one and connect some of the services to it. That's what I tried to say.

**Comment by kevgo** [comment]
Ah, I see, sorry for the confusion! :)  I'd like us (the developer ecosystem) to start approaching persistence as "one database cluster per service". At least for the production environment in the cloud. We can then group some of these databases together if we want to, for example to save money. What I want to get away from is starting off with one main database, and then breaking out a few other databases. That's the old manual and monolithic way of thinking, where setting up databases was hard and laborious, and we tried to minimize that process. There is no more main database in a micro-service world, similar to how there is no main code base from which we extract a few services once in a while. 

So, "main" database instead of "pet" database would have been the better word choice here.

**Comment by arekkas** [comment]
Ah now it makes more sense! I think so too, when you give people one mysql cluster for everything, they will immediately start creating foreign key constraints :100:
