### ISSUE TITLE
Install guide is missing `brew install pkg-config` instruction (OSX)

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#138]
Here's what I did:

```
$ brew install zmq
$ sudo npm i -g exosphere-sdk
```

Here's what I got:

```
89358 verbose unlock done using /Users/aeneas/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
89359 silly rollbackFailedOptional Starting
89360 silly rollbackFailedOptional Finishing
89361 silly runTopLevelLifecycles Starting
89362 silly runTopLevelLifecycles Finishing
89363 silly install printInstalled
89364 verbose stack Error: zmq@2.15.3 install: `node-gyp rebuild`
89364 verbose stack Exit status 1
89364 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
89364 verbose stack     at emitTwo (events.js:100:13)
89364 verbose stack     at EventEmitter.emit (events.js:185:7)
89364 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
89364 verbose stack     at emitTwo (events.js:100:13)
89364 verbose stack     at ChildProcess.emit (events.js:185:7)
89364 verbose stack     at maybeClose (internal/child_process.js:827:16)
89364 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
89365 verbose pkgid zmq@2.15.3
89366 verbose cwd /Users/aeneas/workspaces/go/src/github.com/ory-am/editor-platform/editor-platform
89367 error Darwin 15.6.0
89368 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "exosphere-sdk"
89369 error node v5.7.0
89370 error npm  v3.6.0
89371 error code ELIFECYCLE
89372 error zmq@2.15.3 install: `node-gyp rebuild`
89372 error Exit status 1
89373 error Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
89373 error Make sure you have the latest version of node.js and npm installed.
89373 error If you do, this is most likely a problem with the zmq package,
89373 error not with npm itself.
89373 error Tell the author that this fails on your system:
89373 error     node-gyp rebuild
89373 error You can get information on how to open an issue for this project with:
89373 error     npm bugs zmq
89373 error Or if that isn't available, you can get their info via:
89373 error     npm owner ls zmq
89373 error There is likely additional logging output above.
89374 verbose exit [ 1, true ]

```

**Comment by arekkas** [comment]
I made npm work with my regular account (not root) because I thought it might have to do something with it, unfortunately it didn't help:

```
$ brew install zmq
$ npm i -g exosphere-sdk
```

```
/Users/aeneas/.npm-packages/bin/exo -> /Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/bin/exo

> zmq@2.15.3 install /Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/zmq
> node-gyp rebuild

/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/zmq
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/Users/aeneas/.npm-packages/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "exosphere-sdk"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.15.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aeneas/npm-debug.log
npm ERR! code 1
``

**Comment by arekkas** [comment]
So, I now installed pkg-config using brew (`brew install pkg-config`) and am able to install exosphere. I haven't tried this on windows yet, but node-gyp + windows is always *very* bad on fresh installs. Maybe reconsider using binaries for the exo command, like Go or Rust? I had very good experiences with https://github.com/spf13/cobra which docker, hydra and other popular go projects are using.

**Comment by kevgo** [comment]
One thing that stands out to me is that you use `sudo` for installing npm modules. That should not be done. Did you install Node via `brew install nodejs`?

**Comment by kevgo** [comment]
I am also open to bundling up binary packages containing the Node library and everything if this issue becomes more widespread. I'm not looking forward to having to manage platform-specific binaries, but if it is the less painful route, then that's okay.

**Comment by kevgo** [comment]
The CLI is doing quite a bit, including sophisticated CLI wizards, hence we stuck with Node because it is much more evolved in this area.

**Comment by kevgo** [comment]
But I just refactored the SDK so that we can start changing one command at a time to something else as a test balloon.

**Comment by arekkas** [comment]
> I'm not looking forward to having to manage platform-specific binaries

Hydra is released as binary using github releases for all platforms using https://github.com/mitchellh/gox and travis ci. This kind of stuff is very easy with modern languages :)

> One thing that stands out to me is that you use sudo for installing npm modules. That should not be done. Did you install Node via brew install nodejs?

No I did not but I changed it now in a way that I can install global modules. It was more a "do it once, permissions changed forever" kind of issue that I was to lazy to fix. Still, that doesn't change the fact that it looks like you need the `zmq` and the `pkg-config` dependency installed using brew. This could probably be updated in the installation.md

> The CLI is doing quite a bit, including sophisticated CLI wizards, hence we stuck with Node because it is much more evolved in this area.

I'm not sure what you're doing exactly but I'm 99.9% sure the same thing can be achieved with other languages with reasonable resources :)

I had very good experiences with shipping hydra as a binary. Installing a dependency with a one-off command like `sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn` is simply awesome and works very well when distributing binaries that have no dependencies (like lib-xml or stuff). A multi-step set up that is dependend on third party stuff installed (like installing zmq in the wrong version) is a little error prone and a can get frustrating setting up :)

**Comment by kevgo** [comment]
Thanks for all the pointers, this is super helpful! Can you please point me to where the different binaries for the platforms for Hydra are? I have looked at https://github.com/ory-am/hydra/releases and couldn't find them there. I'm very curious to learn how this is done in other projects!

I agree that the current way of installing Exo needs some improvements. This is next on my list. It should be a simple and straightforward. This is a side effect when almost everybody who uses it is also a core developer and runs straight from a local clone, and we haven't looked at this much at all. 😝 

Just for the sake of argument and fairness, `sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn` requires bash (which doesn't exist on Windows) and curl (which sometimes also doesn't come out of the box). These things are painful to install without a package manager. If there is a package manager, running `brew install exo`, or `sudo apt-get exo`, which then also installs node, zmq, and pkg-config, in the correct versions, is pretty simple and straightforward, no? This is my long-term vision for how the installer works. The other alternative is bundling up node, zmq, and pkg-config into a binary. There are several tools for that, for example [Electron](https://github.com/electron/electron).

How would one implement updates in the setup you describe? The exo binary should be auto-updating. Right now it already gives notifications about new versions. Merely installing things is not enough anymore for user tools.

Another concern about Go is that is it so low level. It feels like almost writing in C. I see a lot of Go developers getting stuck on things like lack of generics and trying to apply type checking on data with very flexible structure. Plus Node has a larger ecosystem. All of this is certainly also a matter of taste. What's your experience here?

All of this together made me go the current route. I'm not saying it's the only correct approach here. But I can see this work equally well to what you describe here (with some elbow grease).

**Comment by arekkas** [comment]
> Thanks for all the pointers, this is super helpful! Can you please point me to where the different binaries for the platforms for Hydra are? I have looked at https://github.com/ory-am/hydra/releases and couldn't find them there. I'm very curious to learn how this is done in other projects!

I lied a bit, I am in the process of setting up automated builds but it works in other projects. The 0.4.0 release for example has binaries built on my macbook for all platforms though (one command). The PR that will solve this is this one: https://github.com/ory-am/hydra/pull/240

> This is a side effect when almost everybody who uses it is also a core developer and runs straight from a local clone, and we haven't looked at this much at all. 

That's what I thought, which is why I'm bringing up this verbose thread :)

> Just for the sake of argument and fairness, sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn requires bash (which doesn't exist on Windows) and curl (which sometimes also doesn't come out of the box).

They have install scripts for windows too, which work with powershell. Brew on the other hand does not exist on windows. Shipping through apt-get et al will get you involved in the whole debian/redhat/suse/... release process, no (doesn't exist on windows)? Still, it would be cool having apt support, but keeping maintainers to constantly update your stuff on the package lists, that's a whole different story.

> Another concern about Go is that is it so low level. It feels like almost writing in C. I see a lot of Go developers getting stuck on things like lack of generics and trying to apply type checking on data with very flexible structure. Plus Node has a larger ecosystem. All of this is certainly also a matter of taste. What's your experience here?

There is so much good software out there that is written in Go/Rust/Typed languages..., this sounds like a very generic criticism which "depends" on the use case. It compiles, it's fast, it's safe and it keeps you sane. It won't solve big data processing nor will it build the nextgen ui for you, but that's not what Go is for and that's not what exo cli is doing neither. IMHO trusting opinions like that isn't much worth if you haven't seriously tried it yourself. There are more than enough large scale production systems that take this approach and that have awesome CLI experiences that are built on top of go and cobra.

JavaScript has so many quirks and shitty build systems and shitty package management and shitty stack traces and hours of webpack setups and node-gyp and other crap and yet **people build great software with it**. Before node came out nobody would have ever thought that you would ever have a javascript based CLI and influental engineers said this was the worst idea ever (putting javascript on the server). Yet, great software exists, it has a large ecosystem and it solves some issues better than other languages.

This isn't about which langauge is superiority, it's about what you want to solve and how you solve it. Shipping binaries with no dependencies for a CLI is smart and easy and cool and it will make people think "WOW is this ALL I have to do to set up a microservice environment???". This thought will be achieved with an installation that takes one CLI command and no dependencies.

If I, as a developer who works 24/7 has troubles setting up exo then what about the not so experienced developers, who are usually not resiliant to errors? I know that this is all very rough yet but I want to show you the things that will probably have issues once you release. Ask @taccurran - he never managed to get npm working on his laptop.

To conclude: why not use the tool that is best for achieving that "WOW" moment instead of getting lost in "it doesn't have generics so I can't build software with it". By listing a couple of options I also tried to get away form "Go is the only chance to solve this". It's not, but it's a choice that makes a lot of sense, because it makes things easier for your users by shipping binaries with no dependencies

**Comment by arekkas** [comment]
This is by the way what a CLI command with cobra looks like:

```
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
	"time"
)

var (
	Version   = "dev-master"
	BuildTime = time.Now().String()
	GitHash   = "undefined"
)

// versionCmd represents the version command
var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Display this binary's version, build time and git hash of this build",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("Version:    %s\n", Version)
		fmt.Printf("Git Hash:   %s\n", GitHash)
		fmt.Printf("Build Time: %s\n", BuildTime)
	},
}

func init() {
	RootCmd.AddCommand(versionCmd)
}
```

https://github.com/ory-am/hydra/blob/042e5318a487979b0252881e84d5ed310c23477e/cmd/version.go

**Comment by arekkas** [comment]
And maybe I need to be a bit more precise on why I think that there could be better choices for the cli command. If you ever had to set up node-gyp on Windows, it's a 1h to 5 days thing that keeps you awake and very angry, as you have to finde the right NET framework and the right dependencies for other stuff (only msvs2012-xyz-foobar that is a broken download link in some out of date readme). As I have seen that exo currently relies on node-gyp, this brings back old nightmares. I don't know if using Go can solve this (because of 0mq dependency), but hey, it's worth a shot.

**Comment by arekkas** [comment]
Sorry, I overlooked:

> How would one implement updates in the setup you describe? The exo binary should be auto-updating. Right now it already gives notifications about new versions. Merely installing things is not enough anymore for user tools.

I don't really know how that works yet, but we're not the first to figure out autoupdating binaries. It's probably something like:

1. check version
2. download new binary
3. replace current binary

There's also something called the update framework (TUF). I never read more than the tag line though ;) https://github.com/flynn/go-tuf

I think it's what flynn uses to update their CLI and cluster nodes.

**Comment by kevgo** [comment]
I hope that https://github.com/felixrieseberg/windows-build-tools alleviates a lot of the Windows issues that plagued so many people a while back. Haven't tried it out though.

**Comment by kevgo** [comment]
Okay, thanks for the elaborate details! I agree that a simple "do this one thing" (or maybe two) to install something is important here, and we should strive for getting there sooner rather than later.

We have looked at all the options you mention here, and use all of them on projects. The problems I mentioned happened on a project that uses an Exosphere-like architecture, that's why I brought them up here. Easy installation is certainly important, there are other issues to consider as well.

If ZMQ and node-gyp turn out to be big headaches, we can throw them out and ship a version of the SDK that has zero dependencies.

**Comment by kevgo** [comment]
Some more thoughts:
* Yes, JavaScript is quirky. But those quirks are mostly around its syntax. The underlying idea is powerful. LiveScript is a re-implementation of that idea, which fixes most of those quirks, and results in a very powerful language that combines some of the best aspects of OO and functional programming without becoming complicated. Go and Rust also have quite a few quirks in their syntax. Haskell is elegant, but has a very steep learning curve.
* JavaScript on the server is a great idea. It's not a coincidence that Node is so successful. Many of the smartest people at Google saw that potential years before Node. Node was not the first attempt to bring JS to the server (see Rhino, Nashorn, and others), but finally good enough to become widespread.
* NPM is not my favorite package manager either (don't get me started). But it does a lot of things better than others (like no more dependency hell). It can be made work, and besides being slow most issues can be addressed. I don't know the perfect package manager either. Vendoring dependencies, as in Go, can also be done in Node. That approach just comes with its own set of tradeoffs, which is why we aren't doing it on this project (yet).
* V8 is one of the most modern and sophisticated runtimes on the planet, very actively developed. Building on top of it is not the worst idea.
* Yes, webpack takes a while to set up, because it does so much. What's the alternative to it?
* You need a compiler if you do serious development. Homebrew needs one, and many high-performance libraries (parsers etc) use C extensions. Not choosing high-performance infrastructure like ZMQ because it makes the installation of a dev SDK harder as an argument can only go so far, at least for pro developers (which are the target group here). Same for having to run `npm i -g exosphere`. Anybody who writes non-trivial server code should not be afraid of such things.
* Stack traces aren't that great, but with good code structuring and TDD that's rarely an issue. 
* Node has pretty sophisticated dev tools that give you flame graphs, debuggers, and other good stuff that is years ahead of the alternative platforms you mention.

Having said all this, you make good points. Given that the installation requires several steps, I could see a Bash-based installation script that 
- installs XCode if needed
- installs Homebrew if needed
- installs Node, pkg-config, zmq if needed
- installs exosphere

It could be run similar to how the Flynn (or Homebrew) installer works, and include the best practices to get this installed for each platform. What do you think?

**Comment by arekkas** [comment]
> Yes, JavaScript is quirky. But those quirks are mostly around its syntax. 

My intention was not to bash JavaScript or the toolchain or your choice of language, I tried to show that despite it's flaws, JS can be used for great projects. Thus Go, despite missing generics (although that's not even 100% true) and assertions (not 100% true either) and lowlevel (not 100% true either as I tried to show with the simple example above), can be used to build great projects too.

> Comparable steps for other platforms. It could be run similar to how the Flynn (or Homebrew) installer works, and include the best practices to get this installed for each platform. What do you think?

Definitely. Please keep in mind though, that multi-stage installers are prone to errors, because dependencies change, systems change. No-dep binaries don't change unless you have a new CPU arch :)

**Comment by kevgo** [comment]
Definitely! I have written a [sizeable app](https://github.com/originate/git-town) in Bash! No question the majority of the new amazing ops infrastructure is in Go, and for good reason. I was just pondering about how much of an impact these things have in real life. I heard anywhere from "not that much" to "kind of annoying", but you are right, that can be said about anything.

No-dep binaries are definitely the most robust way to distribute software. Although once you need to compile C extensions, even that becomes a bit more complicated.

**Comment by arekkas** [comment]
By the way, the flynn founders told dotCloud to use go for their project. They did, and became docker. I believe that one of the reasons for their succes is because they give devs the best UX currently available for running things. Go plays a central role in achieving this. They use cobra too, by the way :)

Gesendet mit meinem HTC

----- Reply message -----
Von: "Kevin Goslar" <notifications@github.com>
An: "Originate/exosphere-sdk" <exosphere-sdk@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Author" <author@noreply.github.com>
Betreff: [Originate/exosphere-sdk] Install guide is missing `brew install pkg-config` instruction (OSX) (#138)
Datum: Fr., Sep. 2, 2016 08:05

Definitely! I have written a [sizeable app](https://github.com/originate/git-town) in Bash! No question the majority of the new amazing ops infrastructure is in Go, and for good reason. I was just pondering about how much of an impact these things have in real life. I heard anywhere from "not that much" to "kind of annoying", but you are right, that can be said about anything.

No-dep binaries are definitely the most robust way to distribute software. Although once you need to compile C extensions, even that becomes a bit more complicated.

**Comment by kevgo** [comment]
Thanks for pushing this, very good conversation! This is definitely the point I'm most unsure about as well. 

> I tried out flynn (after bosh, cloud foundry, open shift). Their concept of client server, installing, running things. It is all one command. It all works on every platform. They even shipped a UI using the default browser and html. The whole experience was what kicked off, in my head: wow, devs and ops are users too and we have to deal with shitty UX much too often.

I think [Electron](http://electron.atom.io) gets as close to the perfect solution here as it gets in 2016. See the many [apps written in it](http://electron.atom.io/apps). Or [Node Webkit](https://github.com/nwjs/nw.js/wiki/List-of-apps-and-companies-using-nw.js). Nothing beats a native app if you want great visual UX. You get desktop notifications, system-wide hotkeys, etc. 

You are right on the money about developer UX. Exosphere is all about that, making development of cloud and AI native apps human-friendly. Here is the setup on a dev machine that I'm aiming for with Exo:
- all external dependencies (databases, services I'm not currently working on, but that my app needs to function) are running inside Docker. So that the dev doesn't have to install and configure dozens of languages, database systems, etc, at particular versions. Even worse, having to run Postgres 7 and 8 in parallel on your machine, because different services require different versions of it.
- the services that are actively worked on are not running inside Docker, but natively the machine's file system. This allows to use whatever editor and Git tool you want, and gives Exo full access to the filesystem. For example to monitor filestystem changes and restart services when that happens. Such things are clunky and brittle from within Docker (we have experience with this).

This means the perfect developer setup (that Exo should encourage) is:
- the dev has a working package manager to easily and reliably install other languages that are needed to work on apps. On Mac thats Homebrew, on Windows Chocolatey, and Linux is golden out of the box. 
- that includes having a working compiler, because the package manager and many of the packages installed usually need that, especially non-trivial apps. 
- there should be no other dependencies besides Exo and the package manager. The rest (Docker, other languages) is installed through it. This means a lot more things become automatable than when relying on manual installs by the user, even if they are easy. 

I don't want to get into the business of "it's easy to install Exo, but then its hard to do anything with it because you still have to install several things in order to actually work on apps". I don't want to have to provide customer support for lots of people around how to install Ruby 2.1.5 on their machines, because they work on a Rails app running inside Exo. I want to say "use your package manager to install all this" or even better "Exo will install this using your package manager for you".

If we require a functioning package manager and compiler, then having certain dependencies for Exo (like ZMQ or Node) is much less of an issue. It becomes trivial. One of Exo's roles is encouraging (and enforcing) best practices and standardizing development environments, without making people feel locked into a proprietary way of doing things. Similar to how Heroku enforced 12-factor apps. Even though that makes things sometimes more complicated than necessary, it's the better way long term, and Heroku is right in enforcing this. 

That's not to say that I don't 100% agree with you that installation of all this should be as easy as possible, otherwise that's a huge impediment. I am bumping up the priority to straighten out the installation, thanks for that feedback!

**Comment by arekkas** [comment]
> I think Electron gets as close to the perfect solution here as it gets in 2016. See the many apps written in it. Or Node Webkit. Nothing beats a native app if you want great visual UX. You get desktop notifications, system-wide hotkeys, etc.

Electron is definitely up there. I think that's the reason why desktop apps have a revival right now!

> all external dependencies (databases, services I'm not currently working on, but that my app needs to function) are running inside Docker. So that the dev doesn't have to install and configure dozens of languages, database systems, etc, at particular versions. Even worse, having to run Postgres 7 and 8 in parallel on your machine, because different services require different versions of it.

💯 

> that includes having a working compiler, because the package manager and many of the packages installed usually need that, especially non-trivial apps.
> there should be no other dependencies besides Exo and the package manager. The rest (Docker, other languages) is installed through it. This means a lot more things become automatable than when relying on manual installs by the user, even if they are easy.

I think both of those things are really good goals. It's maybe ok to install docker manually, because it's a one click install  but the package manager could also just do it for you.

> I don't want to get into the business of "it's easy to install Exo, but then its hard to do anything with it because you still have to install several things in order to actually work on apps". I don't want to have to provide customer support for lots of people around how to install Ruby 2.1.5 on their machines, because they work on a Rails app running inside Exo. I want to say "use your package manager to install all this" or even better "Exo will install this using your package manager for you".

I think that this is the money spot. I can very well imagine that one service relies on Ruby 1.9 and the other on 2.1.5 and you need to develop on both in parallel. Same thing applies to basically any language (node, go, java). It's almost impossible to have two/three/four of these environments run in parallel on the same system, so we should think about this problem from the beginning.

> That's not to say that I don't 100% agree with you that installation of all this should be as easy as possible, otherwise that's a huge impediment. I am bumping up the priority to straighten out the installation, thanks for that feedback!

Awesome, I think figuring that out would be really good!

**Comment by arekkas** [comment]
So, automated x-compile and release [work now](https://github.com/ory-am/hydra/releases/tag/v0.4.2-alpha.4) for Hydra. If you want to see how I did it, you can check out the travis.yml: https://github.com/ory-am/hydra/blob/master/.travis.yml

**Comment by trushton** [comment]
Looks as thought this was taken care of in the PR mentioned above. Closing this issue now.
